name: EAS Build (Android)

on:
  workflow_dispatch:
    inputs:
      profile:
        description: 'Profile do eas.json'
        required: true
        default: preview
        type: choice
        options:
          - development
          - preview
          - preview2
          - preview3
          - production
          - apk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - uses: expo/expo-github-action@c7b66a9c327a43a8fa7c0158e7f30d6040d2481e # v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build on EAS
        run: eas build --platform android --profile ${{ inputs.profile }} --non-interactive
